'use strict';

const goodEntries = [
  'norm',
  'norma',
  'norman',
  'norman*',
  'normanb',
  'normanby',
  'normanby*',
  'norr',
  'norri',
  'norris',
  'norris*',
  'nort',
  'north',
  'north*',
  'northa',
  'northal',
  'northall',
  'northalle',
  'northaller',
  'northallert',
  'northallerto',
  'northallerton',
  'northallerton*',
  'northam',
  'northam*',
  'northamp',
  'northampt',
  'northampto',
  'northampton',
  'northamptons',
  'northamptonsh',
  'northamptonshi',
  'northamptonshir',
  'northamptonshire',
  'northamptonshire*',
  'northb',
  'northbo',
  'northbou',
  'northbour',
  'northbourn',
  'northbourne',
  'northbourne*',
  'northbr',
  'northbro',
  'northbroo',
  'northbrook',
  'northbrook*',
  'northc',
  'northco',
  'northcot'
];

const badEntries = [
  'nort',
  'north',
  'north*',
  'northa',
  'northal',
  'northall',
  'northalle',
  'northaller',
  'northallert',
  'northallerto',
  'northallerton',
  'northallerton*',
  'northam',
  'northam*',
  'northamp',
  'northampt',
  'northampto',
  'northampton',
  'northamptons',
  'northamptonsh',
  'northamptonshi',
  'northamptonshir',
  'northamptonshire',
  'northamptonshire*',
  'northb',
  'northbo',
  'northbou',
  'northbour',
  'northbourn',
  'northbourne',
  'northbourne*',
  'northbr',
  'northbro',
  'northbroo',
  'northbrook',
  'northbrook*',
  'northc',
  'northco',
  'northcot'
];

const docsWithScores = [
  '1:Norman & sons',
  '0',
  '2:The norman clothes',
  '0',
  '3:Best clothes - Norman',
  '0'
]

module.exports = {
  goodEntries,
  badEntries,
  docsWithScores
};